source 'https://rubygems.org'

ruby '3.4.4'

gem 'rails', '~> 7.1.3'
gem 'pg', '>= 1.1'
gem 'puma', '~> 6.4'
gem 'bcrypt', '~> 3.1'
gem 'jwt', '~> 2.7'
gem 'rack-cors', '~> 2.0'
gem 'stripe', '~> 11.0'
gem 'bootsnap', '>= 1.16.0', require: false

group :development, :test do
  gem 'rspec-rails', '~> 6.1'
end

group :development do
  gem 'listen', '~> 3.8'
  gem 'spring'
  gem 'dotenv-rails'
end

